### ISSUE TITLE
RL Course 1 Week 2 Blog

### ISSUE THREAD

**Issue by sezan92** [sezan92/sezan92.github.io#30]
## Objective

This issue is to track work on RL course 1 Week 2 Note blog. The comments will be primary draft.

**Comment by sezan92** [comment]
## Update 2023/09/04

- [x] ccomleted W2L1 video https://github.com/sezan92/sezan92.github.io/pull/32/commits/d7a11447ea48209365f3c3150b6b56a287250c4c

**Comment by sezan92** [comment]
## Update 2023/09/21

- [x]  working on L1 video notes, https://github.com/sezan92/sezan92.github.io/pull/32/commits/36e28ca186c5eeb08e4432c8295c5b678e65c4ae

**Comment by sezan92** [comment]
## Update 2023/09/24

- [x] video 1 done, https://github.com/sezan92/sezan92.github.io/pull/32/commits/e788fec58d845c8e25c3edd42b22041dd67f06d8

**Comment by sezan92** [comment]
# Update 2023/09/25

- [x]  Week 2 , Module 1, video 2 done.

### TODO

- [x] need to summarize the video 2

**Comment by sezan92** [comment]
## Update 2023/09/26

-  [x] Video 2 is still hard to explain very quickly. I need to write a draft first.

### TODO

- [x]  Write a draft

**Comment by sezan92** [comment]
## Update 2023/09/27

- [x]  started writing draft for video 2

### TODO
- [x] need to make hand drawn diagrams.

**Comment by sezan92** [comment]
## Update 2023/10/02

- [x] initial draft 
![IMG_0681](https://github.com/sezan92/sezan92.github.io/assets/11025093/3f59e549-a6cb-44b0-8397-da8ffab5bca4)

## TODO

- [x] make a clear diagram

**Comment by sezan92** [comment]
# Update 2023/10/03

- [x] better version https://share.goodnotes.com/s/eaUs1kLcWxgMBnBb8pCSs3 , need to share more presentable and interactive version to the blog

### TODO

- [x] initial written form should be prepared first.

**Comment by sezan92** [comment]
## Update 2023/10/04

- [x] created  block diagram snapshots in https://photos.app.goo.gl/MVgVaTkcWDwnbrF99

### TODO

- [x] add them to the blog post

**Comment by sezan92** [comment]
## Update 2023/10/06

- [x] started explaining https://github.com/sezan92/sezan92.github.io/pull/32/commits/75bd762810ded19c6f193f9a476e1ae0993e3741

### TODO

- [x]  complete the intuition

**Comment by sezan92** [comment]
## Update 2023/10/08

- [x]  updated intuition https://github.com/sezan92/sezan92.github.io/pull/32/commits/7b483569bfd254b6ecd1416848331d061e9586fa

### TODO

- [x]  start W2L3

**Comment by sezan92** [comment]
## Update 2023/10/10

- [x]  started W2L3. WIP

### TODO

- [x] complete summarizing W2L3
- [ ] start W2L4

**Comment by sezan92** [comment]
## Update 2023/10/11

-  [x]  https://github.com/sezan92/sezan92.github.io/pull/32/commits/421b677cb87bdfcc19e322cb4609b4da4bdd913b

### TODO

- [x] start W2L4

**Comment by sezan92** [comment]
## Update 2023/10/12

- [x] started W2L4 , upto 5:00 minute

### TODO

- [x]  complete W2L4

**Comment by sezan92** [comment]
## Update 2023/10/16

- [x] completed W2L4. need to summarize

**Comment by sezan92** [comment]
## Update 2023/10/19

- [x] started W2L4 https://github.com/sezan92/sezan92.github.io/pull/32/commits/29301efee4d9190879c813df58a400813e9ce0d3

### TODO

- [x] complete

**Comment by sezan92** [comment]
## Update 2023/11/09

- [x] completed W2L5 and W2L6 Videos . All of them

### TODO

- [x]  summarize them

**Comment by sezan92** [comment]
## Update 2023/11/14

-  [x] https://github.com/sezan92/sezan92.github.io/commit/22979c562243085379464f2619f11fb4fd4b0b28

### TODO

-   [x] complete summary

**Comment by sezan92** [comment]
## Update 2023/11/16

- [x] completed in https://github.com/sezan92/sezan92.github.io/pull/32/commits/5cf00342c732251e2bf0a65e0adf00bdcf13f279

### TODO

- [x]  revise the last video
- [x] check with grammarly
- [x] merge PR

**Comment by sezan92** [comment]
## Update 2023/11/17

- completed with #32
