### ISSUE TITLE
RL Course 1 Week 3 blog

### ISSUE THREAD

**Issue by sezan92** [sezan92/sezan92.github.io#33]

**Comment by sezan92** [comment]
## update 2023/11/21

- [x]  https://github.com/sezan92/sezan92.github.io/pull/34

### TODO

 - [x]  start W3L2 from 1.09

**Comment by sezan92** [comment]
## Update 2023/11/28

- [x] w3l2 done . https://github.com/sezan92/sezan92.github.io/pull/34/commits/71a30601c291efcafe4de8b0b9f60ce47e775bc6

### TODO

- [x] summarize w3L2

**Comment by sezan92** [comment]
## Update 2023/12/13

- [x]  added intuition https://github.com/sezan92/sezan92.github.io/pull/34/commits/40a1345d196144dbf869d50f9ac13bcb0dddfeae

### TODO

- [x]  update stochastic policy

**Comment by sezan92** [comment]
## Update 2024/01/08

- [x]  added intuition about stochastic policy https://github.com/sezan92/sezan92.github.io/pull/34/commits/2e2208f8863f6629fc35fcc5982c5aef7e6350d4

### TODO

-  [x]  add eqn /pictures from the lectures.

**Comment by sezan92** [comment]
## Update 2024/01/10

- [x]  policy video done

### TODO

- [x] start value function video.

**Comment by sezan92** [comment]
# 2024/01/15 

- [x] started value function video 4:17
- [ ] 

## todo

- [x] complete video

**Comment by sezan92** [comment]
## Update 2024/01/17

-  [x]  completed the video for week 3

### TODO

-  [x] work on intuition

**Comment by sezan92** [comment]
## Update 2024/01/23

- [x] https://github.com/sezan92/sezan92.github.io/pull/34/commits/2e609fab31a9daf77e08e206c767732f47ca1611

### TODO

- [x]  add details with reward.
