### ISSUE TITLE
RL Course 1 Week 4 blog

### ISSUE THREAD

**Issue by sezan92** [sezan92/sezan92.github.io#35]

**Comment by sezan92** [comment]
## Update 2024/01/31

- [x] Started W4 L1
- [x] Completed video

### TODO

- [x]  Start writeup

**Comment by sezan92** [comment]
## Update 2024/02/08

- #37 
- [x] upto 1:27

### TODO

- [ ] write the other details

**Comment by sezan92** [comment]
## Update 2024/02/17

- [x] upto 1:57

**Comment by sezan92** [comment]
## Update 2024/03/07

- [x]  upto C1W4L3 v1 3:24


### TODO

- [ ] understand strictly better policyt
- [x] complete the video

**Comment by sezan92** [comment]
## Update 2024/03/16

- [x] C1W4L3 done

### TODO

- [ ] complete C1W4L4

**Comment by sezan92** [comment]
## Update 2024/04/16

-  [ ]. Unable to intuition for iterative policy evaluatio n network
- [x] need to re thinking.

**Comment by sezan92** [comment]
## 2024/04/19

- [x]  intuition started https://github.com/sezan92/sezan92.github.io/pull/37/commits/9ba63eabadf6a199d204509549e9500697f97ab7

### TODO

- [x]  complete the intuition with the diagrams

**Comment by sezan92** [comment]
## Update 2024/04/30

- [x] made some diagrams. 
![pass_4](https://github.com/sezan92/sezan92.github.io/assets/11025093/5f6e8f78-3294-4074-bab4-8f3240adc968)
![pass_3](https://github.com/sezan92/sezan92.github.io/assets/11025093/105a4a06-f30a-4c1d-a8d0-fb8689cf59a8)
![pass_2](https://github.com/sezan92/sezan92.github.io/assets/11025093/21b5e513-238b-4ad0-a12d-963b1130cf5f)
![initial_image](https://github.com/sezan92/sezan92.github.io/assets/11025093/a18a8562-d9cd-48d8-81a6-eac1af522dd6)

i have some problems with the diagrams, the diagram does not follow proper bellman equation with probability. 


### TODO

- [ ] make the diagram with the bellman equation, with proper probability https://excalidraw.com/

**Comment by sezan92** [comment]
## Update 2024/05/16

- [x]  Updated pictures

### TODO

- [x]  Write down intuition

**Comment by sezan92** [comment]
## Update 2024/05/29

- [x] wrote intuition 

### TODO

- [x]  start https://www.coursera.org/learn/fundamentals-of-reinforcement-learning/lecture/ICAfp/iterative-policy-evaluation

**Comment by sezan92** [comment]
## Update 2024/06/04

- [x] watched video https://www.coursera.org/learn/fundamentals-of-reinforcement-learning/lecture/FVd6r/policy-improvement
- [x]  watched videos https://www.coursera.org/learn/fundamentals-of-reinforcement-learning/lecture/Xv32P/policy-iteration

### TODO 

- [x]  writeup on the above videos

**Comment by sezan92** [comment]
## Update 2024/06/14

- [x] writeup done on the policy improvement and iteration videos

### TODO

- [x]  start watching https://www.coursera.org/learn/fundamentals-of-reinforcement-learning/lecture/tusGq/flexibility-of-the-policy-iteration-framework
- [ ] writeup on this

**Comment by sezan92** [comment]
## Update 2024/06/19

- [x] watched tart watching https://www.coursera.org/learn/fundamentals-of-reinforcement-learning/lecture/tusGq/flexibility-of-the-policy-iteration-framework 
- [x] and https://www.coursera.org/learn/fundamentals-of-reinforcement-learning/lecture/ANQkM/efficiency-of-dynamic-programming

### TODO

- [ ]  Writeup on this.

**Comment by sezan92** [comment]
## Update 2024/06/23

- [x] I have checked the Generalized Policy iteration video, got the difference with the Policy Iteration framework. need to have a good writeup

### TODO

- [x]  make the difference intuitive

**Comment by sezan92** [comment]
## Update 2024/06/26

- [x] Wrote about General Policy Iteration. or value iteration

### TODO

- [x]  Explain Dynamic Programming and how it is useful

**Comment by sezan92** [comment]
Completed in #37
