### ISSUE TITLE
RL course 2 Week 1 Blog

### ISSUE THREAD

**Issue by sezan92** [sezan92/sezan92.github.io#41]
## Objective

This issue is about writup on week 1 RL course 2 blog

**Comment by sezan92** [comment]
## Update 2024/07/30

- [ ]  started from Week 2. Definition of Monte Carlo method done.

### ToDO

- [ ] https://www.coursera.org/learn/sample-based-learning-methods/lecture/7F85i/using-monte-carlo-for-prediction

**Comment by sezan92** [comment]
## Update 2024/08/09

- [x] #42 started

### TODO

- [ ]  complete it.

**Comment by sezan92** [comment]
## Update 2024/08/22

- [x] video 2 done. could not get it well. check the book

### TODO

- [x] check the book on monte carlo black jack

**Comment by sezan92** [comment]
## Update 2024/08/28

-  [x] wrote intuition

### TODO

- [x] Start video 3

**Comment by sezan92** [comment]
## Update 2024/09/02

- [x] started video 3 and 4. that means monte carlo action value update and general policy iteration

### TODO

- [x] update the intuition on penalty (slight wrong)
- [ ] write up inteution
- [ ]

**Comment by sezan92** [comment]
## 2024/09/11

- [x] updated the penalty example.
- [x] started video on exploring starts, name "solving blackjack example".

### TODO

- [ ] complete and intuition on exploring starts, and epsilon soft policy in one go

**Comment by sezan92** [comment]
## Update 2024/09/24

- [x] watched video https://www.coursera.org/learn/sample-based-learning-methods/lecture/zlI9l/epsilon-soft-policies

### TODO

- [x] make intuition on the exploring start vs epsilon soft policy

**Comment by sezan92** [comment]
### Update 2024/10/01

- [x] Started intuition with Goal keeping

### TODO

- [x] complete it

**Comment by sezan92** [comment]
### Update 2024/10/18

- [x]  GK intuition for exploration done.

### TODO

- [ ]  complete and start next video (after exploration)

**Comment by sezan92** [comment]
## Update 2024/10/22

- [x] need to explain for exploring start and epsilon soft policy

### TODO

- [x] complete the intuition

**Comment by sezan92** [comment]
## Update 2024/10/31

- [x] started exploring start. need better intuition

### TODO

- [x] explain

**Comment by sezan92** [comment]
## Update 2024/11/14

-  [x] completed epsilon soft policy intuition (epsilon soft policy video)

### TODO

- [ ] start from the next video.

**Comment by sezan92** [comment]
## 2024/11/20

- [x] added reference
- [x] Screenshot , paste it
![IMG_1242](https://github.com/user-attachments/assets/8c72b2a7-5163-4404-9df4-f7bc5d3e0881)


### TODO

- [x] paste the screenshot
- [ ] Start from next video

**Comment by sezan92** [comment]
### Update 2024/12/06

-  [x] pasted screenshot

### TODO 

- [x] start next video (video after epsilon soft policy)

**Comment by sezan92** [comment]
## update 2024/12/11

- [x] watched https://www.coursera.org/learn/sample-based-learning-methods/lecture/zjkqu/why-does-off-policy-learning-matter

### TODO

- [x] summarize and blog about it

**Comment by sezan92** [comment]
## Update 2024/12/18

- [x] added off policy details

### TODO

- [x] add the diagrams shown in the video for intuition

**Comment by sezan92** [comment]
## Update 2024/12/25

- [x] wrote about off policy learning

### TODO

- [x] watch video importance sampling

**Comment by sezan92** [comment]
## Update 2024/12/27

- [x] watched video on importance sampling

### TODO

- [ ] write up

**Comment by sezan92** [comment]
## Update 2025/01/09

- [ ] importance sampling understand more: https://jonathan-hui.medium.com/rl-importance-sampling-ebfb28b4a8c6

**Comment by sezan92** [comment]
## Update 2025/01/19

- [x] watch video https://youtu.be/C3p2wI4RAi8?si=aNPnwaFa4yc6EWNI

**Comment by sezan92** [comment]
## Update 2025/01/29

- [x]  watched the video. kind of got idea

### TODO

-  [x] rewatch the video
- [x] check with RL book

**Comment by sezan92** [comment]
## Update 2025/02/07

- [x]  read the RL book . coul not get better idea
- [ ] need to check another last source and rewatch the video

### TODO

- [ ] rewatch the video and another source for intuition. ask bing chat about intuition

**Comment by sezan92** [comment]
## 2025/02/20

- [x]  watched https://www.coursera.org/learn/sample-based-learning-methods/lecture/0Oe1R/off-policy-monte-carlo-prediction 

### TODO

- [x]  explain both importance sampling and the above video

**Comment by sezan92** [comment]
## Update 2025/02/28

- [x] wrote somewhat about the importance sampling

### TODO

- [x] complete try to understand more and intuition more about importance sampling

**Comment by sezan92** [comment]
## Update 2025/03/17

- [x] I have read the details on the RL book. some idea about why off-policy learning was named such. but got confused about importance sampling reasoning

### TODO

- [x] this is enough, I will add a TODO on importance sampling intuition, and add the mathematical details on it.

**Comment by sezan92** [comment]
## Update 2025/04/08

- [ ]. watched this video https://www.youtube.com/watch?v=S3LAOZxGcnk best intuition.
