### ISSUE TITLE
Hindsight is 20-20 Blog

### ISSUE THREAD

**Issue by sezan92** [sezan92/sezan92.github.io#6]
## Objective
The objective of this issue is to write blog on the projects/ courses completed in 2020

## Tasks
- [x] #7 
- [ ] Self Driving Car Nanodegree Blog
- [ ] Self Driving Car Specialization Blog
- [ ] Reinforcement Learning Speciailization Blog
- [ ] AI for Medicine Specialization
- [ ] Crafting Quality Code
- [ ] Discrete Mathematics Course
- [ ] Graph Theory Course (Ongoing)
- [ ] Introduction to Economics Course
