### ISSUE TITLE
Workera Blog

### ISSUE THREAD

**Issue by sezan92** [sezan92/sezan92.github.io#7]
## Objective
The objective of this issue is to track on Workera Blog

## Tasks
- [x] Write a draft blog
- [x] Get  Editing 
- [x] Show to workera
- [x] Publis

**Comment by sezan92** [comment]
## update
- [ ]  Started the introduction
## TODO
- [ ] Topics
- - [ ] Assessment
- - [ ] Learning
- - [ ] Certificate
-  [ ] Improvement

**Comment by sezan92** [comment]
## Basic starting workflow
![32186755-3088-49E2-9D31-6B6E99ABFC92](https://user-images.githubusercontent.com/11025093/181000526-13295938-95ae-4fa4-b372-3bbaf9c90a56.jpeg)

**Comment by sezan92** [comment]
## workera

- [x] background
- [x] problem description
- [x] how we met
- [x] how does  it feel
- [x] what is the cost
- [x] result

**Comment by sezan92** [comment]
## update 2022/07/26

### background
after starting to work on ai engineer. i got stuck in same types of projects. before that I used to learn a lot of different stuff, latest techs as well. but as I am working 8 hour full day, I am not 100% keeping pace with ever changing technology
..to be continued

**Comment by sezan92** [comment]
## update 2022/07/27
which made a problem in the case of job hunting. in the interviews they will ask about latest technologies. if you are not keeping up pace, you will be in a problem. 

another issue was mathematics of machine learning. in the case of real world works we don't need maths always. we might forget the mathematical issues while working too long in one project. 

another problem is , in the jobs there are many coding tests. but being non-cs guy , I didn't know what kind of problems I might have to face. then ,I came to know about this website Workera.

###TODO
- [x] how I got to know workers and description

**Comment by sezan92** [comment]
# update 2022/08/02

## How did I get to know about workers

I cannot really remember actually. most likely from deeplearning.ai website. for some reason I went to the website and found this one. All credits to Allah. 

## How is workera

Okay basic introduction as of 2022/08/02. Workera has will ask you about your desired skill set. My one is `deeplearning researcher` . . There are others like `AI literate` , `Data analyst` etc. you choose your one. 

##### TODO
- [x] continue describing workera

**Comment by sezan92** [comment]
## How is workera (contd)

According to your choice, they will give recommend you skills to test. For me it was ,

- Deep Learning
- Machine Learning (obviously)
- Algorithmic coding
- Software Engineering
- Mathematics
- Data Science

Under each skill set , they have some set questions to test you. Based on the scoring of the first attestment, they will suggest you what skills you are stronger or weaker. Based on each question which you failed or could not answer in time, they will suggest you website / youtube video / coursera course or a video from that course. 

For me, it was obvious. I was very poor in algorithmic coding. Poorest of all skills. So naturally workera suggested resources on fundamental algorithm and data structure videos. Next to algoritmic coding, I was also bad at mathematics. So they suggested a lot of resources for Mathematics. (to be contd)

**Comment by sezan92** [comment]
## How is workera (contd)
 
Apart from that, my strong zones were not that strong at all.  I was surprised (and happy) to find a lack of understanding of deep learning and machine learning fundamentals!  These tests helped me fill up my necessary knowledge very fast. By suggesting videos of immense resources of Coursera.!

## Cost and result

The best part of all this is that workera is Free! ( i mean as of yet 2022/09/20) . i.e. you will get a full evaluation of your skills from this platform without paying anything!

But it is not free for companies! If some company wants to use it for the development of its workers, I think they need to pay.
